memory = "512"
disk_quota = "1024"
CLOUD_FOUNDRY_USERNAME = ""
CLOUD_FOUNDRY_PASSWORD = "" 
CLOUD_FOUNDRY_ORG = "client-NGCAP"
CLOUD_FOUNDRY_SPACE = "terraform-test2"
rabbitmq_service_plan = "medium-standalone"
postgres_service_plan = "postgres-micro-dev"
redis_service_plan = "redis-development"
ngcap_cs_tag = "0.2.694"
ngcap_js_tag = "0.2.471"
DOCKER_REGISTRY_USERNAME = ""
DOCKER_REGISTRY_PASSWORD = ""

