pipeline {
	agent { node { label 'DEPLOY-TEST' } }
	stages{
                stage('Secure Agent') {
                        agent { node ( "${env.NODE_NAME}-work" ) }
                        stages {
				stage('HELLO WORLD') {
					steps {
						echo 'HELLO WORLD'
					}
				}
			}
		}
	}

}
