pipeline {
	agent { node { label 'DEPLOY-TEST' } }
	environment {
		HTTPS_PROXY="http://amec.zscaler.philips.com:9480/"
		HTTP_PROXY="http://amec.zscaler.philips.com:9480/"
	}
	parameters {
		booleanParam(name: 'INIT_SERVICES', defaultValue: false, description: 'Initialize services')
	}
	stages {
                stage('Secure Agent') {
                        agent { node ( "${env.NODE_NAME}-work" ) }
                       	stages {
				stage('Call terraform init') {
					steps {
						withCredentials([file(credentialsId: 'terraform_creds', variable: 'TERRAFORMRC')]) {
							dir('src') {
								withEnv(["TF_CLI_CONFIG_FILE=${TERRAFORMRC}"]) {
					 				bat 'E:\\terraform_0.12.25_windows_amd64\\terraform.exe init -plugin-dir=E:\\terraform-plugins -backend-config=backends\\backend-ngcap.hcl'
								}
							}
						}
					}
				}

			}	
		}
	}

}
