{
 "title": "Calc Execution Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_exe",
    "label": "instance_exe",
    "query": "label_values({application=\"execution\"},instance)"
   },
   {
    "name": "instance_dispatcher",
    "label": "instance_dispatcher",
    "query": "label_values({TenantId=~\"$tenant_id\",application=\"dispatcher\"},instance)"
   },
   { "name": "tenant_id", "query": "label_values(TenantId)" }
  ]
 },
 "panels": [
  {
   "title": "Calc Execution Rate (Execution)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_Execution_count{TenantId=~\"$tenant_id\",instance=~\"$instance_exe\"}[1m])) by (CalcName,State)"
    }
   ]
  },
  {
   "title": "Load All Inputs for Calc",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_LoadAllInputs_sum{TenantId=~\"$tenant_id\",instance=~\"$instance_dispatcher\"}[5m])/rate(ngcap_LoadAllInputs_count{instance=~\"$instance_dispatcher\"}[5m])) by (CalcName)"
    }
   ]
  },
  {
   "title": "C# Calc Execution Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_Execution_sum{TenantId=~\"$tenant_id\",State=\"Completed\",instance=~\"$instance_exe\"}[1m])/rate(ngcap_Execution_count{State=\"Completed\",instance=~\"$instance_exe\"}[1m])) by (CalcName,Runtime)\n\n"
    }
   ]
  },
  {
   "title": "Calc Execution Rate (publish CEB)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_RequestForExecution{TenantId=~\"$tenant_id\",instance=~\"$instance_dispatcher\"}[5m])) by (CalcName)"
    },
    {}
   ]
  },
  {
   "title": "C# Calc Execution Failures",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ngcap_Execution_count{TenantId=~\"$tenant_id\",State!=\"Completed\",instance=~\"$instance_exe\"}) by (CalcName,Runtime,State)\n\n"
    }
   ]
  },
  {
   "title": "Debounced Calc Requests",
   "type": "graph",
   "description": "Ignored Calc Requests because the execution of the calculation is already scheduled.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Left" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_ExecutionDebounced{TenantId=~\"$tenant_id\",instance=~\"$instance_dispatcher\"}[5m])) by (CalcName)"
    }
   ]
  },
  {
   "title": "Calculation Evaluated No Execute",
   "type": "graph",
   "description": "After loading the inputs, required values are missing and execution is aboarded",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Left" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_NotPublished[5m])) by (CalcName)"
    }
   ]
  },
  {
   "title": "Locks not available by calc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Concurrency Lock",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_LockNotAvail[5m])) by (CalcName)"
    }
   ]
  },
  {
   "title": "Debounce L2",
   "type": "graph",
   "description": "Ignored Calc Requests because the execution of the calculation has not completed yet",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_ExecutionDebouncedL2[5m])) by (CalcName)"
    }
   ]
  }
 ]
}