{
 "title": "NGCAP Data Interfaces",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Deployment", "query": "label_values(space_name)" }
  ]
 },
 "panels": [
  {
   "title": "FHIR Adds Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_AddResource_count{space_name=~\"^$Deployment.*$\"}[5m])) by (ResourceType)"
    }
   ]
  },
  {
   "title": "Generic Documents Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(ngcap_AddDocument_count{space_name=~\"^$Deployment.*$\"}[5m])) by (DocumentType)"
    }
   ]
  },
  {
   "title": "FHIR Adds Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_AddResource_sum{space_name=~\"^$Deployment.*$\"}[5m])/rate(ngcap_AddResource_count{space_name=~\"^$Deployment.*$\"}[5m])) by (ResourceType)"
    }
   ]
  },
  {
   "title": "Generic Document Add Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_AddDocument_sum{space_name=~\"^$Deployment.*$\"}[1m])/rate(ngcap_AddDocument_count{space_name=~\"^$Deployment.*$\"}[1m])) by (Operation,DocumentType)"
    }
   ]
  },
  {
   "title": "FHIR Query Resources Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_FhirQueryResource_sum{space_name=~\"^$Deployment.*$\"}[5m])/rate(ngcap_FhirQueryResource_count{space_name=~\"^$Deployment.*$\"}[5m])) by (ResourceType)\n\n"
    }
   ]
  },
  {
   "title": "Generic Query Documents Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_GenericQueryResource_sum{space_name=~\"^$Deployment.*$\"}[5m])/rate(ngcap_GenericQueryResource_count{space_name=~\"^$Deployment.*$\"}[5m])) by (DocumentType)\n\n\n"
    }
   ]
  },
  {
   "title": "HTTP Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_DotNet_HttpRequest_sum{space_name=~\"^$Deployment.*$\"}[5m])/rate(ngcap_DotNet_HttpRequest_count{space_name=~\"^$Deployment.*$\"}[5m])) by  (controller,action,method,status)"
    }
   ]
  },
  {
   "title": "Generic Mark for Cleanup Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_GenericMarkDocument_sum{space_name=~\"^$Deployment.*$\"}[5m])/rate(ngcap_GenericMarkDocument_count{space_name=~\"^$Deployment.*$\"}[5m])) by (DocumentType)\n\n\n"
    }
   ]
  },
  {
   "title": "FHIR Mark for Cleanup Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_FhirMarkResource_sum{space_name=~\"^$Deployment.*$\"}[5m])/rate(ngcap_FhirMarkResource_count{space_name=~\"^$Deployment.*$\"}[5m])) by (ResourceType)\n\n\n\n"
    }
   ]
  },
  {
   "title": "FHIR Archive Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_FhirArchive_sum{space_name=~\"^$Deployment.*$\"}[5m])/rate(ngcap_FhirArchive_count{space_name=~\"^$Deployment.*$\"}[5m])) by (ResourceType)"
    }
   ]
  },
  {
   "title": "Generic Archive Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ngcap_GenericArchive_sum{space_name=~\"^$Deployment.*$\"}[5m])/rate(ngcap_GenericArchive_count{space_name=~\"^$Deployment.*$\"}[5m])) by (ResourceType)"
    }
   ]
  }
 ]
}